default-extensions:
  - AllowAmbiguousTypes
  - ApplicativeDo
  - BangPatterns
  - BinaryLiterals
  - BlockArguments
  - ConstrainedClassMethods
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - DisambiguateRecordFields
  - DoAndIfThenElse
  - DuplicateRecordFields
  - EmptyCase
  - EmptyDataDecls
  - EmptyDataDeriving
  - ExistentialQuantification
  - ExplicitForAll
  - ExplicitNamespaces
  - ExtendedDefaultRules
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTSyntax
  - GADTs
  - GeneralizedNewtypeDeriving
  - HexFloatLiterals
  - ImplicitParams
  - ImportQualifiedPost
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - LiberalTypeSynonyms
  - MagicHash
  - MonadComprehensions
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NamedWildCards
  - NoMonomorphismRestriction
  - NoStarIsType
  - NondecreasingIndentation
  - NumDecimals
  - NumericUnderscores
  - OverloadedLabels
  - OverloadedStrings
  - PackageImports
  - ParallelArrays
  - ParallelListComp
  - PartialTypeSignatures
  - PatternGuards
  - PatternSynonyms
  - PolyKinds
  - PostfixOperators
  - QuantifiedConstraints
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - RecursiveDo
  - RelaxedLayout
  - RelaxedPolyRec
  - RoleAnnotations
  - ScopedTypeVariables
  - StandaloneDeriving
  - StandaloneKindSignatures
  - TransformListComp
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeInType
  - TypeOperators
  - TypeSynonymInstances
  - UnboxedSums
  - UnboxedTuples
  - UnicodeSyntax
  - ViewPatterns
  - OverloadedRecordDot
dependencies:
  - "base-noprelude >= 4.7"
  - MyPrelude
  - containers
  - transformers
  - mtl
  - comonad
  - profunctors
  - semigroupoids
  - bifunctors
  - bytestring
  - vector
  - ansi-terminal
  - aeson
  - text
  - directory
  - random
  - random-shuffle
  - megaparsec
library:
  source-dirs: src
name: prl
verbatim:
  cabal-version: 2.4
executable:
  main: Main.hs
  source-dirs: app
  dependencies: prl
